# Don't allow new windows to be larger than the screen.
autofit-larger=100%x100%
# Enable hardware decoding if available, =yes is implied.
hwdec
# Spaces don't have to be escaped.
osd-playing-msg=File: ${filename}
# https://www.reddit.com/r/mpv/comments/11ytoue/a_beginners_guide_to_customizing_your_media_player/
profile=low-latency
osd-bar=no

# uosc will draw its own window controls and border if you disable window border
border=no
