# Reference: https://github.com/i3/i3/blob/next/etc/config
#
# Environmental workarounds needed as of 20241110:
#
# from https://nikitabobko.github.io/AeroSpace/guide#a-note-on-mission-control:
# $ defaults write com.apple.dock expose-group-apps -bool true && killall Dock
#
# from https://nikitabobko.github.io/AeroSpace/guide#a-note-on-displays-have-separate-spaces
# $ defaults write com.apple.spaces spans-displays -bool true && killall SystemUIServer


start-at-login = true

# Run Sketchybar together with AeroSpace
# sketchbar has a built-in detection of already running process,
# so it won't be run twice on AeroSpace restart
after-startup-command = [
  'exec-and-forget sketchybar',
  'exec-and-forget borders active_color=0xffffa500 inactive_color=0xff494d64 width=7.0 hidpi=on ax_focus=off'
]

# Notify Sketchybar about workspace change
exec-on-workspace-change = ['/bin/bash', '-c',
    'sketchybar --trigger aerospace_workspace_change FOCUSED_WORKSPACE=$AEROSPACE_FOCUSED_WORKSPACE'
]




# i3 doesn't have "normalizations" feature that why we disable them here.
# But the feature is very helpful.
# Normalizations eliminate all sorts of weird tree configurations that don't make sense.
# Give normalizations a chance and enable them back.
enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

# Mouse follows focus when focused monitor changes
on-focused-monitor-changed = ['move-mouse monitor-lazy-center']
on-focus-changed = ['move-mouse window-lazy-center']


[mode.main.binding]
alt-enter = 'exec-and-forget /opt/homebrew/bin/wezterm cli spawn --new-window'


# what is wrapped focus?
ctrl-h = 'focus --boundaries-action wrap-around-the-workspace left'
ctrl-j = 'focus --boundaries-action wrap-around-the-workspace down'
ctrl-k = 'focus --boundaries-action wrap-around-the-workspace up'
ctrl-l = 'focus --boundaries-action wrap-around-the-workspace right'

ctrl-shift-h = 'move left'
ctrl-shift-j = 'move down'
ctrl-shift-k = 'move up'
ctrl-shift-l = 'move right'

ctrl-f = 'fullscreen'

ctrl-s = 'layout v_accordion' # 'layout stacking' in i3
ctrl-w = 'layout h_accordion' # 'layout tabbed' in i3
ctrl-e = 'layout tiles horizontal vertical' # 'layout toggle split' in i3

alt-shift-space = 'layout floating tiling' # 'floating toggle' in i3

# Not supported, because this command is redundant in AeroSpace mental model.
# See: https://nikitabobko.github.io/AeroSpace/guide#floating-windows
#alt-space = 'focus toggle_tiling_floating'

# `focus parent`/`focus child` are not yet supported, and it's not clear whether they
# should be supported at all https://github.com/nikitabobko/AeroSpace/issues/5
# alt-a = 'focus parent'

alt-1 = 'workspace 1'
alt-2 = 'workspace 2'
alt-3 = 'workspace 3'
alt-4 = 'workspace 4'
alt-5 = 'workspace 5'
alt-6 = 'workspace 6'
alt-7 = 'workspace 7'
alt-8 = 'workspace 8'
alt-9 = 'workspace 9'
alt-0 = 'workspace 10'

alt-shift-1 = 'move-node-to-workspace 1'
alt-shift-2 = 'move-node-to-workspace 2'
alt-shift-3 = 'move-node-to-workspace 3'
alt-shift-4 = 'move-node-to-workspace 4'
alt-shift-5 = 'move-node-to-workspace 5'
alt-shift-6 = 'move-node-to-workspace 6'
alt-shift-7 = 'move-node-to-workspace 7'
alt-shift-8 = 'move-node-to-workspace 8'
alt-shift-9 = 'move-node-to-workspace 9'
alt-shift-0 = 'move-node-to-workspace 10'

alt-shift-c = 'reload-config'

alt-r = 'mode resize'

alt-b = 'workspace B' # for Browser
alt-c = 'workspace C' # for SMS
alt-n = 'workspace N' # for Notes
alt-p = 'workspace P' # for Passwords
alt-t = 'workspace T' # for Terminal
alt-z = 'workspace Z' # for Zen Browser

[mode.resize.binding]
h = 'resize width -50'
j = 'resize height +50'
k = 'resize height -50'
l = 'resize width +50'
enter = 'mode main'
esc = 'mode main'

[mode.service.binding]
esc = ['reload-config', 'mode main']
r = ['flatten-workspace-tree', 'mode main'] # reset layout
#s = ['layout sticky tiling', 'mode main'] # sticky is not yet supported https://github.com/nikitabobko/AeroSpace/issues/2
f = ['layout floating tiling', 'mode main'] # Toggle between floating and tiling layout
backspace = ['close-all-windows-but-current', 'mode main']

alt-shift-h = ['join-with left', 'mode main']
alt-shift-j = ['join-with down', 'mode main']
alt-shift-k = ['join-with up', 'mode main']
alt-shift-l = ['join-with right', 'mode main']

[exec.env-vars]
PATH ="/usr/local/bin:/usr/local/go/bin:${HOME}/.cargo/bin:${HOME}/.local/bin:${HOME}/Library/Python/3.8/bin:/opt/homebrew/bin:${HOME}/Downloads/google-cloud-sdk/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin"

[[on-window-detected]]
if.app-id = 'org.kagi.kagimacOS'
run = 'move-node-to-workspace B'

[[on-window-detected]]
if.app-id = 'com.google.Chrome'
run = 'move-node-to-workspace B'

[[on-window-detected]]
if.app-id = 'com.github.wez.wezterm'
run = 'move-node-to-workspace T'

[[on-window-detected]]
if.app-id = 'com.tinyspeck.slackmacgap'
run = 'move-node-to-workspace C'

[[on-window-detected]]
if.app-id = 'com.apple.Music'
run = 'move-node-to-workspace M'

[[on-window-detected]]
if.app-id = 'com.apple.MobileSMS'
run = 'move-node-to-workspace C'

[[on-window-detected]]
if.app-id = 'com.apple.Passwords'
run = 'move-node-to-workspace P'

[[on-window-detected]]
if.app-id = 'com.apple.Notes'
run = 'move-node-to-workspace N'

[[on-window-detected]]
if.app-id = 'org.mozilla.com.zen.browser'
run = 'move-node-to-workspace Z'

[gaps]
inner.horizontal = 15
inner.vertical =   15
outer.left =       10
outer.bottom =     10
outer.top =        15
outer.right =      10


# Notify Sketchybar about workspace change
# exec-on-workspace-change = ['/bin/bash', '-c',
#    'sketchybar --trigger aerospace_workspace_change FOCUSED=$AEROSPACE_FOCUSED_WORKSPACE'
#]
