format = """
$os$hostname$directory$git_branch$git_status
$character"""

add_newline = true

[hostname]
format = "[$hostname](bold blue) "
disabled = true

[os]
format = "[$symbol](bold blue) "
disabled = false

[os.symbols]
Macos = "󰀵"
Linux = ""
# For Synology NAS, would need custom module: "󱘖"

[directory]
format = "[$path]($style)[$read_only]($read_only_style) "
home_symbol = "󱂵 "
read_only = " "
truncation_length = 100
truncate_to_repo = false

[git_branch]
format = "[$symbol$branch]($style) "
symbol = " "

[git_status]
format = '([$all_status$ahead_behind]($style) )'
style = "bold blue"

[character]
success_symbol = "[➜](bold green)"
error_symbol = "[➜](bold red)"
